"""empty message

Revision ID: 4294585e3fb5
Revises: 77fbdd8bcf33
Create Date: 2019-05-14 18:04:30.578028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4294585e3fb5'
down_revision = '77fbdd8bcf33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=100), nullable=True))
    op.drop_index('login', table_name='user')
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'login')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('login', 'user', ['login'], unique=True)
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
